name: Hello kevin

on: workflow_dispatch

env:
  NAME: Kevin

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Dit Bonjour"
        if: ${{ env.NAME != 'Kevin'}}
        run: echo "Coucou $NAME ! Tu n'es pas Kevin ?! oO "
      - name: "Coucou Kevin"
        if: ${{env.NAME == 'Kevin'}}
        run: echo "Salut $NAME ! Tu as l'air en forme <3"
