name: Matrix

on: workflow_dispatch

jobs:
  exemple-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perso : ['Joe', 'Jack', 'Avrel', 'Souhaib']
        fruits : ['Pomme', 'Poire', 'Peche', 'Banane']

    steps:
      - name: Phrase a dire
        run: echo "${{matrix.perso}} mange une ${{matrix.fruits}}"